const { OpenAI } = require('openai');

const PRESET_BACKGROUNDS = [
    {
        id: "abstract_dark_waves",
        name: "Dark Waves",
        category: "Abstract",
        url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: "neon_geometric",
        name: "Neon Geometric",
        category: "Modern",
        url: "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: "minimal_gradient",
        name: "Soft Gradient",
        category: "Minimal",
        url: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: "sleek_architecture",
        name: "Sleek Arch",
        category: "Corporate",
        url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: "space_stars",
        name: "Deep Space",
        category: "Dark",
        url: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=2048&auto=format&fit=crop"
    },
    {
        id: "soft_pastels",
        name: "Pastel Dream",
        category: "Light",
        url: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?q=80&w=2029&auto=format&fit=crop"
    }
];

async function generateCustomBackground(prompt) {
    if (!process.env.OPENAI_API_KEY) {
        throw new Error("OPENAI_API_KEY is not configured for image generation.");
    }

    const openai = new OpenAI({
        apiKey: process.env.OPENAI_API_KEY,
    });

    const engineeredPrompt = `A high-quality, professional presentation background image. No text, no words. Abstract, sleek, and modern. Theme: ${prompt}. Cinematic lighting, 8k resolution.`;

    try {
        const response = await openai.images.generate({
            model: "dall-e-3",
            prompt: engineeredPrompt,
            n: 1,
            size: "1024x1024",
            quality: "standard",
        });

        if (response.data && response.data.length > 0) {
            return {
                url: response.data[0].url,
                prompt: prompt
            };
        } else {
            throw new Error("No image generated by DALL-E.");
        }
    } catch (error) {
        console.error("[BackgroundService] Error generating image:", error);
        throw error;
    }
}

function getPresets() {
    return PRESET_BACKGROUNDS;
}

module.exports = {
    generateCustomBackground,
    getPresets
};
